namespace QueryCraft.Adapters.Models;

/// <summary>
/// Contains metadata information about a query execution, including the generated query
/// and pagination parameters used.
/// </summary>
/// <remarks>
/// <para>
/// This class provides transparency into the query execution process by exposing
/// the actual query string generated by the adapter and the pagination parameters
/// that were applied to the results.
/// </para>
/// <para>
/// The metadata is useful for debugging, performance analysis, logging, and providing
/// insights into how filters and pagination are translated into the underlying
/// data source query language.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var metadata = new QueryMetadata
/// {
///     QueryString = "SELECT * FROM Users WHERE (Age > 18 AND IsActive = 1) ORDER BY Name LIMIT 10 OFFSET 20",
///     PaginationQuery = new PaginationQuery 
///     { 
///         PageSize = 10, 
///         PageNumber = 3 
///     }
/// };
/// </code>
/// </example>
public class QueryMetadata
{
    /// <summary>
    /// Gets or sets the query string that was generated and executed against the data source.
    /// </summary>
    /// <value>
    /// A string representation of the query that was executed, such as SQL, MongoDB query,
    /// or other data source-specific query language.
    /// </value>
    /// <remarks>
    /// <para>
    /// The query string provides insight into how the filter criteria were translated
    /// into the underlying data source's native query language. This is valuable for
    /// debugging, performance optimization, and understanding the query execution.
    /// </para>
    /// <para>
    /// The format and content of the query string depend on the specific adapter
    /// implementation and the underlying data source type.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // SQL example
    /// QueryString = "SELECT * FROM Users WHERE Age > @p0 AND Name IN (@p1, @p2)";
    /// 
    /// // MongoDB example
    /// QueryString = "{ $and: [ { age: { $gt: 18 } }, { name: { $in: ['John', 'Jane'] } } ] }";
    /// 
    /// // LINQ example
    /// QueryString = "users.Where(u => u.Age > 18 && new[] { \"John\", \"Jane\" }.Contains(u.Name))";
    /// </code>
    /// </example>
    public string QueryString { get; set; }

    /// <summary>
    /// Gets or sets the pagination query parameters that were applied to the results.
    /// </summary>
    /// <value>
    /// A <see cref="PaginationQuery"/> object containing the pagination parameters
    /// used during query execution, or null if no pagination was applied.
    /// </value>
    /// <remarks>
    /// <para>
    /// This property records the pagination parameters that were actually used
    /// during the query execution, which may be useful for reconstructing the
    /// query or understanding the result set boundaries.
    /// </para>
    /// <para>
    /// The value may be null if the original query did not specify pagination
    /// or if the adapter does not support pagination.
    /// </para>
    /// </remarks>
    public PaginationQuery? PaginationQuery { get; set; }
}